# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=35, verbose_name='Nombre')),
                ('lastName', models.CharField(blank=True, max_length=35, verbose_name='Apellidos')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Número de teléfono')),
                ('gender', models.CharField(blank=True, choices=[('', 'Sin especificar'), ('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo')),
                ('birthdate', models.DateField(blank=True, verbose_name='Fecha de nacimiento')),
                ('ocupation', models.CharField(blank=True, choices=[('', 'Sin especificar'), ('E', 'Estudiante'), ('T', 'Trabajador')], max_length=1, verbose_name='Ocupación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('pet', models.CharField(blank=True, choices=[('', 'Ninguna'), ('P', 'Perro'), ('G', 'Gato'), ('O', 'Otros')], max_length=1, verbose_name='Mascota')),
                ('isSmoker', models.BooleanField(default=False, verbose_name='Fumador')),
                ('lookingIn', models.CharField(blank=True, max_length=35, verbose_name='Ciudad en la que buscas piso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
