# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numHabitaciones', models.IntegerField(default=1)),
                ('precio', models.IntegerField()),
                ('habitacionesDisponibles', models.IntegerField(default=1)),
                ('gastosIncluidos', models.BooleanField(default=False)),
                ('fotos', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('comunidadAutonoma', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('codigoPostal', models.IntegerField()),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='casa',
            name='descripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.descripcion'),
        ),
    ]
