# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='created_date',
            new_name='diaCreacion',
        ),
        migrations.RenameField(
            model_name='casa',
            old_name='author',
            new_name='propietario',
        ),
        migrations.AlterField(
            model_name='casa',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Direccion'),
        ),
    ]
