# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_casa_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
